python "$(dirname "${BASH_SOURCE[0]}")/clean_weibo.py" \
  --dataset "Logistic12/weiboDataWithCommentByTheme" \
  --output "output/cleaned_weibo.jsonl" \
  --metrics "output/clean_metrics.json" \
  --raw-output "output/raw_weibo.jsonl" \
  --streaming "1" \
  --batch-size 200 \
  --print-every 100 \
  --min-effective-len 5 \
  --max-len-truncate 500 \
  --max-len-drop 1000 \
  --near-dup-sim 0.9 \
  --drop-sensitive "true" \
  --ai-enable "${AI_ENABLE:-true}" \
  --ai-on-sensitive-only "true" \
  --ai-sample-rate "${AI_SAMPLE_RATE:-1.0}" < /dev/null